/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockAdjustmentsRouteImport } from './routes/stock-adjustments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierLedgerSupplierIdRouteImport } from './routes/supplier-ledger.$supplierId'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.invoice.$id'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentsRoute = StockAdjustmentsRouteImport.update({
  id: '/stock-adjustments',
  path: '/stock-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierLedgerSupplierIdRoute =
  SupplierLedgerSupplierIdRouteImport.update({
    id: '/supplier-ledger/$supplierId',
    path: '/supplier-ledger/$supplierId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/invoice/$id',
  path: '/print/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/customers'
    | '/inventory'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/stock-adjustments'
    | '/suppliers'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/customers'
    | '/inventory'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/stock-adjustments'
    | '/suppliers'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/customers'
    | '/inventory'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/stock-adjustments'
    | '/suppliers'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StockAdjustmentsRoute: typeof StockAdjustmentsRoute
  SuppliersRoute: typeof SuppliersRoute
  SupplierLedgerSupplierIdRoute: typeof SupplierLedgerSupplierIdRoute
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustments': {
      id: '/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/stock-adjustments'
      preLoaderRoute: typeof StockAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-ledger/$supplierId': {
      id: '/supplier-ledger/$supplierId'
      path: '/supplier-ledger/$supplierId'
      fullPath: '/supplier-ledger/$supplierId'
      preLoaderRoute: typeof SupplierLedgerSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/invoice/$id': {
      id: '/print/invoice/$id'
      path: '/print/invoice/$id'
      fullPath: '/print/invoice/$id'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StockAdjustmentsRoute: StockAdjustmentsRoute,
  SuppliersRoute: SuppliersRoute,
  SupplierLedgerSupplierIdRoute: SupplierLedgerSupplierIdRoute,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
