/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StockHistoryRouteImport } from './routes/stock-history'
import { Route as StockAdjustmentsRouteImport } from './routes/stock-adjustments'
import { Route as SetupWizardRouteImport } from './routes/setup-wizard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdjustStockRouteImport } from './routes/adjust-stock'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierLedgerSupplierIdRouteImport } from './routes/supplier-ledger.$supplierId'
import { Route as PurchaseIdRouteImport } from './routes/purchase.$id'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as PrintPurchaseIdRouteImport } from './routes/print.purchase.$id'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.invoice.$id'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StockHistoryRoute = StockHistoryRouteImport.update({
  id: '/stock-history',
  path: '/stock-history',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentsRoute = StockAdjustmentsRouteImport.update({
  id: '/stock-adjustments',
  path: '/stock-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWizardRoute = SetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustStockRoute = AdjustStockRouteImport.update({
  id: '/adjust-stock',
  path: '/adjust-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierLedgerSupplierIdRoute =
  SupplierLedgerSupplierIdRouteImport.update({
    id: '/supplier-ledger/$supplierId',
    path: '/supplier-ledger/$supplierId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PurchaseIdRoute = PurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any)
const PrintPurchaseIdRoute = PrintPurchaseIdRouteImport.update({
  id: '/print/purchase/$id',
  path: '/print/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/invoice/$id',
  path: '/print/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjust-stock': typeof AdjustStockRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-history': typeof StockHistoryRoute
  '/super-admin': typeof SuperAdminRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjust-stock': typeof AdjustStockRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-history': typeof StockHistoryRoute
  '/super-admin': typeof SuperAdminRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adjust-stock': typeof AdjustStockRoute
  '/billing': typeof BillingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/stock-adjustments': typeof StockAdjustmentsRoute
  '/stock-history': typeof StockHistoryRoute
  '/super-admin': typeof SuperAdminRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/supplier-ledger/$supplierId': typeof SupplierLedgerSupplierIdRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/purchase/$id': typeof PrintPurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjust-stock'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profit'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/setup-wizard'
    | '/stock-adjustments'
    | '/stock-history'
    | '/super-admin'
    | '/suppliers'
    | '/inventory/history'
    | '/purchase/$id'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
    | '/print/purchase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjust-stock'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profit'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/setup-wizard'
    | '/stock-adjustments'
    | '/stock-history'
    | '/super-admin'
    | '/suppliers'
    | '/inventory/history'
    | '/purchase/$id'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
    | '/print/purchase/$id'
  id:
    | '__root__'
    | '/'
    | '/adjust-stock'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/login'
    | '/products'
    | '/profit'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/setup-wizard'
    | '/stock-adjustments'
    | '/stock-history'
    | '/super-admin'
    | '/suppliers'
    | '/inventory/history'
    | '/purchase/$id'
    | '/supplier-ledger/$supplierId'
    | '/print/invoice/$id'
    | '/print/purchase/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdjustStockRoute: typeof AdjustStockRoute
  BillingRoute: typeof BillingRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfitRoute: typeof ProfitRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupWizardRoute: typeof SetupWizardRoute
  StockAdjustmentsRoute: typeof StockAdjustmentsRoute
  StockHistoryRoute: typeof StockHistoryRoute
  SuperAdminRoute: typeof SuperAdminRoute
  SuppliersRoute: typeof SuppliersRoute
  PurchaseIdRoute: typeof PurchaseIdRoute
  SupplierLedgerSupplierIdRoute: typeof SupplierLedgerSupplierIdRoute
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
  PrintPurchaseIdRoute: typeof PrintPurchaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-history': {
      id: '/stock-history'
      path: '/stock-history'
      fullPath: '/stock-history'
      preLoaderRoute: typeof StockHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustments': {
      id: '/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/stock-adjustments'
      preLoaderRoute: typeof StockAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-wizard': {
      id: '/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof SetupWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjust-stock': {
      id: '/adjust-stock'
      path: '/adjust-stock'
      fullPath: '/adjust-stock'
      preLoaderRoute: typeof AdjustStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-ledger/$supplierId': {
      id: '/supplier-ledger/$supplierId'
      path: '/supplier-ledger/$supplierId'
      fullPath: '/supplier-ledger/$supplierId'
      preLoaderRoute: typeof SupplierLedgerSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id': {
      id: '/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof PurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/print/purchase/$id': {
      id: '/print/purchase/$id'
      path: '/print/purchase/$id'
      fullPath: '/print/purchase/$id'
      preLoaderRoute: typeof PrintPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/invoice/$id': {
      id: '/print/invoice/$id'
      path: '/print/invoice/$id'
      fullPath: '/print/invoice/$id'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InventoryRouteChildren {
  InventoryHistoryRoute: typeof InventoryHistoryRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryHistoryRoute: InventoryHistoryRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdjustStockRoute: AdjustStockRoute,
  BillingRoute: BillingRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfitRoute: ProfitRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupWizardRoute: SetupWizardRoute,
  StockAdjustmentsRoute: StockAdjustmentsRoute,
  StockHistoryRoute: StockHistoryRoute,
  SuperAdminRoute: SuperAdminRoute,
  SuppliersRoute: SuppliersRoute,
  PurchaseIdRoute: PurchaseIdRoute,
  SupplierLedgerSupplierIdRoute: SupplierLedgerSupplierIdRoute,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
  PrintPurchaseIdRoute: PrintPurchaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
